### ISSUE TITLE
KubernetesExecutor broken with  Airflow 1.10.1 + Airflow operator

### ISSUE THREAD

**Issue by barney-s** [GoogleCloudPlatform/airflow-operator#31]
@dimberman 

Open Issues:

1. In 1.10.1 release of Airflow, the AirflowExecutor hardcodes the dag source to /tmp/dags for gitsync. With latest master hardcoding is removed. But latest master is not stable.
2. Airflow operator does not create/set the configmap for k8sexecutor config section.

**Comment by jcunhasilva** [comment]
@barney-s is there any updates on this issue?

I tried using the KubernetesExecutor but I'm getting git authentication issues in the worker pods.
The worker pod has an init container to clone the git repo but the authentication details are missing:
```
  initContainers:
  - env:
    - name: GIT_SYNC_REPO
      value: https://github.com/MyOrg/my-repo.git
    - name: GIT_SYNC_BRANCH
      value: MY_BRANCH
    - name: GIT_SYNC_ROOT
      value: /tmp
    - name: GIT_SYNC_DEST
      value: dags
    - name: GIT_SYNC_ONE_TIME
      value: "true"
    image: gcr.io/google-containers/git-sync-amd64:v2.0.5
```

I tried looking at the code and see where this is defined but I can't seem to find it.
