### ISSUE TITLE
GIT authentication is not working during cluster setup

### ISSUE THREAD

**Issue by jcunhasilva** [GoogleCloudPlatform/airflow-operator#44]
I created the following cluster using the airflow operator deployed directly from Google Cloud Marketplace:
```
apiVersion: airflow.k8s.io/v1alpha1
kind: AirflowCluster
metadata:
  name: my-airflow-cluster
spec:
  executor: Kubernetes
  ui:
    replicas: 1
    version: "1.10.1"
  scheduler:
    version: "1.10.1"
  worker:
    version: "1.10.1"
  config:
    airflow:
      AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 100
  dags:
    subdir: "pipelines/"
    git:
      repo: "https://github.com/MyOrg/my-repo.git"
      once: false
      branch: master
      user: MY_USER
      cred:
        name: MY_GIT_SECRET
  airflowbase:
    name: my-airflow-base
```

Once the cluster is up and running, I get the following error in the git-sync side container:
`Cloning into '/git'...\nfatal: could not read Username for 'https://github.com': No such device or address\n"`

So it seems the container is struggling with GIT authentication. When inspecting the container's environment variables I can see that these variables were created:
```
GIT_PASSWORD	
defined as key password of MY_GIT_SECRET
GIT_USER	
my_user
```

I stumbled upon this issue in the git-sync project where other people had issues setting up authentication:
https://github.com/kubernetes/git-sync/issues/126

In this issue we have the following configuration
```
...
    - name: GIT_SYNC_USERNAME
      valueFrom:
        secretKeyRef:
          name: git-creds
          key: username
    - name: GIT_SYNC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: git-creds
          key: password
...
```

so it seems the airflow-operator is using the wrong prefix for the authentication ("GIT_" instead of "GIT_SYNC_")
