### ISSUE TITLE
Add support for SQL Proxy connections in our workers

### ISSUE THREAD

**Issue by jcunhasilva** [GoogleCloudPlatform/airflow-operator#57]
Currently if we want to connect to a Cloud SQL database in our workers/dags, we need to create a connection using the database's Public or Private IP.
The best way to connect to these databases is through SQL Proxy side containers as described here:
https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine

We should have a way of specifying predefined sql proxy connections to be attached to the scheduler or worker pods. We could define these connections directly in the cluster configuration.

The configuration spec should be similar as the one currently available in the base yaml configuration:
```
spec:
  sqlproxy:
    project: kubeflow-193622
    region: us-central1
    instance: testsql-cluster
```
