### ISSUE TITLE
Support for secrets in the spec.config.airflow field

### ISSUE THREAD

**Issue by jcunhasilva** [GoogleCloudPlatform/airflow-operator#60]
Environment variables are passed to our airflow containers using the "airflow" field:
```
config:
    airflow:
      AIRFLOW__CORE__FERNET_KEY: "MY_SECRET_KEY"
```
In this case we are defining the fernet key which is sensitive information. We should be able to use secrets in this field.

We have this block in airflow.go:
```
for _, k := range keys {
    env = append(env, corev1.EnvVar{Name: k, Value: sp.Config.AirflowEnv[k]})
}
```

Maybe we can have a separate field ("airflowSecrets") to inject secret values:
```
for _, k := range keys {
    env = append(env, corev1.EnvVar{Name: k, ValueFrom: envFromSecret(sp.Config.AirflowSecrets[k].name, sp.Config.AirflowSecrets[k].field)})
}
```

**Comment by barney-s** [comment]
Is there list of config entries that need a secret ?
Trying to enumerate them.

**Comment by jcunhasilva** [comment]
As far as I know we have these ones:
AIRFLOW__CORE__FERNET_KEY
AIRFLOW__WEBSERVER__SECRET_KEY
AIRFLOW__SMTP__SMTP_PASSWORD

**Comment by barney-s** [comment]
I can make the change. But verification is a different beast.
But if you have done something please do feel free to submit and i can review.

**Comment by jcunhasilva** [comment]
I prefer the first one since it gives us more flexibility (we can even inject additional env variables to be used in our dags).
But how do you reference the secret field that holds the password? How about this structure:
```
config:
   airflow:
        AIRFLOW__CORE__SOMETHING: "SOMETHING"
   airflowsecrets:
      MY_SECRET_ENV:
         name: secretname
         field: secretfield 
```

**Comment by jcunhasilva** [comment]
@barney-s I'm testing this issue with this configuration:
```
airflowsecret:
- env: "AIRFLOW__CORE__FERNET_KEY"
   secret: "my-secret"
   field: "fernet-key"
```

When the scheduler get's deployed it throws an error initializing the pod because it has a empty secret:
```
- name: ""
   valueFrom:
      secretKeyRef:
         key: ""
```

I'm trying to debug the code but I guess it's related with the spec deep copy in zz_generated_deepcopy.go:
```
	if in.AirflowSecretEnv != nil {
		in, out := &in.AirflowSecretEnv, &out.AirflowSecretEnv
		*out = make([]SecretEnv, len(*in))
		copy(*out, *in)
	}
```

**Comment by jcunhasilva** [comment]
Please ignore my previous comment. My cluster spec was not correct:
```
airflowsecret:
- Env: "AIRFLOW__CORE__FERNET_KEY"
   Secret: "my-secret"
   Field: "fernet-key"
```
