### ISSUE TITLE
GCS & 1.10.2

### ISSUE THREAD

**Issue by zifeo** [GoogleCloudPlatform/airflow-operator#80]
Using dag provision through gcs and the latest release continously crash loop.

```shell
airflow.exceptions.AirflowConfigException: In kubernetes mode the following must be set in the `kubernetes` config section: `dags_volume_claim` or `dags_volume_host` or `dags_in_image` or `git_repo and git_branch and git_dags_folder_mount_point`
```

Is there anything config specific to bypass this? I've tried setting manually the `dags_volume_host` which does not seem to be passed to the actual pods.

**Comment by barney-s** [comment]
Thanks for the PR. Would you elaborate and share the CRs ?

**Comment by zifeo** [comment]
@barney-s This is more a question than a PR. Is there anything I can add?

**Comment by Pritesh-Patel** [comment]
Running into this problem as well.

**Comment by Pritesh-Patel** [comment]
@zifeo I got past it by adding config `AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "True"`

eg:

`
apiVersion: airflow.k8s.io/v1alpha1
kind: AirflowCluster
metadata:
  name: airflow-cluster
spec:
  config:
    airflow:
      AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "100"
      AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "True"
`

This was not the easiest to find might make sense to put it in the k8s executor examples? @barney-s

**Comment by zifeo** [comment]
@Pritesh-Patel Could you share the full config file (except the bucket name of course)? I have tried the same without success.

**Comment by Pritesh-Patel** [comment]
@zifeo 

```
apiVersion: airflow.k8s.io/v1alpha1
kind: AirflowCluster
metadata:
  name: airflow-cluster
spec:
  config:
    airflow:
      AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "100"
      AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "True"
  executor: Kubernetes
  ui:
    replicas: 1
    version: "1.10.2"
  scheduler:
    version: "1.10.2"
  worker:
    version: "1.10.2"
  dags:
    subdir: ""
    gcs:
      bucket: "airflow-dags"
  airflowbase:
    name: airflow-base
```

Unfortunately after this I ran into SQL errors and decided to give up on this and use the helm chart. I would preferably like to use this - but i dont have the time to debug the issue. Let me know if you get further!
