### ISSUE TITLE
Add Env variable to Container

### ISSUE THREAD

**Issue by jingwangumg** [GoogleCloudPlatform/airflow-operator#99]
How to overwrite airflow config with environment variables? 
I tried the following in the AirflowCluster yaml, the the operator did not pick it up. 
```
spec:
  config:
    airflow:
      AIRFLOW__WEBSERVER__NAVBAR_COLOR: #f5f5f5
```
